version: '3'
services:
  nodejs-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: node-api
    volumes:
       - ./server:/usr/src/app/server
       - /usr/src/app/server/node_modules
  vue-ui:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: vue-ui
    volumes:
       - ./client:/usr/src/app/client
       - /usr/src/app/client/node_modules