/* tslint:disable */
/* eslint-disable */
/**
 * csgo-stratbook api
 * Stratbook REST API
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AddStrategyDto
 */
export interface AddStrategyDto {
    /**
     * 
     * @type {string}
     * @memberof AddStrategyDto
     */
    gameMap: AddStrategyDtoGameMap;
    /**
     * 
     * @type {string}
     * @memberof AddStrategyDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AddStrategyDto
     */
    type: AddStrategyDtoType;
    /**
     * 
     * @type {string}
     * @memberof AddStrategyDto
     */
    side: AddStrategyDtoSide;
    /**
     * 
     * @type {string}
     * @memberof AddStrategyDto
     */
    note?: string;
    /**
     * 
     * @type {string}
     * @memberof AddStrategyDto
     */
    videoLink?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum AddStrategyDtoGameMap {
    Dust2 = 'DUST_2',
    Mirage = 'MIRAGE',
    Overpass = 'OVERPASS',
    Nuke = 'NUKE',
    Vertigo = 'VERTIGO',
    Inferno = 'INFERNO',
    Train = 'TRAIN'
}
/**
    * @export
    * @enum {string}
    */
export enum AddStrategyDtoType {
    Pistol = 'PISTOL',
    Force = 'FORCE',
    Buyround = 'BUYROUND'
}
/**
    * @export
    * @enum {string}
    */
export enum AddStrategyDtoSide {
    Ct = 'CT',
    T = 'T'
}



