/* tslint:disable */
/* eslint-disable */
/**
 * csgo-stratbook api
 * Stratbook REST API
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { TeamServerConnection } from './team-server-connection';

/**
 * 
 * @export
 * @interface GetTeamResponse
 */
export interface GetTeamResponse {
    /**
     * 
     * @type {string}
     * @memberof GetTeamResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof GetTeamResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof GetTeamResponse
     */
    website: string;
    /**
     * 
     * @type {TeamServerConnection}
     * @memberof GetTeamResponse
     */
    server: TeamServerConnection;
    /**
     * 
     * @type {string}
     * @memberof GetTeamResponse
     */
    joinCode: string;
    /**
     * 
     * @type {string}
     * @memberof GetTeamResponse
     */
    avatar: string;
    /**
     * 
     * @type {string}
     * @memberof GetTeamResponse
     */
    manager: string;
}


