/* tslint:disable */
/* eslint-disable */
/**
 * csgo-stratbook api
 * Stratbook REST API
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { GetUtilityCratedByResponse } from './get-utility-crated-by-response';

/**
 * 
 * @export
 * @interface GetUtilityResponse
 */
export interface GetUtilityResponse {
    /**
     * 
     * @type {string}
     * @memberof GetUtilityResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof GetUtilityResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof GetUtilityResponse
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof GetUtilityResponse
     */
    playerSide: GetUtilityResponsePlayerSide;
    /**
     * 
     * @type {string}
     * @memberof GetUtilityResponse
     */
    type: GetUtilityResponseType;
    /**
     * 
     * @type {string}
     * @memberof GetUtilityResponse
     */
    mouseButton: GetUtilityResponseMouseButton;
    /**
     * 
     * @type {boolean}
     * @memberof GetUtilityResponse
     */
    crouch: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GetUtilityResponse
     */
    jump: boolean;
    /**
     * 
     * @type {string}
     * @memberof GetUtilityResponse
     */
    movement: GetUtilityResponseMovement;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetUtilityResponse
     */
    images: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof GetUtilityResponse
     */
    videoLink: string;
    /**
     * 
     * @type {GetUtilityCratedByResponse}
     * @memberof GetUtilityResponse
     */
    createdBy: GetUtilityCratedByResponse;
    /**
     * 
     * @type {string}
     * @memberof GetUtilityResponse
     */
    createdAt: string;
}

/**
    * @export
    * @enum {string}
    */
export enum GetUtilityResponsePlayerSide {
    Ct = 'CT',
    T = 'T'
}
/**
    * @export
    * @enum {string}
    */
export enum GetUtilityResponseType {
    Flash = 'FLASH',
    Grenade = 'GRENADE',
    Smoke = 'SMOKE',
    Molotov = 'MOLOTOV'
}
/**
    * @export
    * @enum {string}
    */
export enum GetUtilityResponseMouseButton {
    Left = 'LEFT',
    Right = 'RIGHT',
    Leftright = 'LEFTRIGHT'
}
/**
    * @export
    * @enum {string}
    */
export enum GetUtilityResponseMovement {
    Still = 'STILL',
    Walk = 'WALK',
    Run = 'RUN'
}



