/* tslint:disable */
/* eslint-disable */
/**
 * csgo-stratbook api
 * Stratbook REST API
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProfileUpdateDto
 */
export interface ProfileUpdateDto {
    /**
     * 
     * @type {string}
     * @memberof ProfileUpdateDto
     */
    userName: string;
    /**
     * 
     * @type {string}
     * @memberof ProfileUpdateDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof ProfileUpdateDto
     */
    password: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProfileUpdateDto
     */
    completedTutorial: boolean;
    /**
     * true if user name should be replaced in strategies
     * @type {boolean}
     * @memberof ProfileUpdateDto
     */
    updateStrategies: boolean;
}


