/* tslint:disable */
/* eslint-disable */
/**
 * csgo-stratbook api
 * Stratbook REST API
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateUtilityPositionDto
 */
export interface UpdateUtilityPositionDto {
    /**
     * Utility id
     * @type {string}
     * @memberof UpdateUtilityPositionDto
     */
    id: string;
    /**
     * Old position where the utility was located
     * @type {number}
     * @memberof UpdateUtilityPositionDto
     */
    oldPosition: number;
    /**
     * New position where the utility should be placed at
     * @type {number}
     * @memberof UpdateUtilityPositionDto
     */
    newPosition: number;
}


