/* tslint:disable */
/* eslint-disable */
/**
 * csgo-stratbook api
 * Stratbook REST API
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateStrategyDto
 */
export interface UpdateStrategyDto {
    /**
     * strategy sub-document id
     * @type {string}
     * @memberof UpdateStrategyDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateStrategyDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateStrategyDto
     */
    note: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateStrategyDto
     */
    side: UpdateStrategyDtoSide;
    /**
     * 
     * @type {string}
     * @memberof UpdateStrategyDto
     */
    type: UpdateStrategyDtoType;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateStrategyDto
     */
    active: boolean;
    /**
     * 
     * @type {string}
     * @memberof UpdateStrategyDto
     */
    videoLink: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateStrategyDto
     */
    content: string;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateStrategyDto
     */
    shared: boolean;
}

/**
    * @export
    * @enum {string}
    */
export enum UpdateStrategyDtoSide {
    Ct = 'CT',
    T = 'T'
}
/**
    * @export
    * @enum {string}
    */
export enum UpdateStrategyDtoType {
    Pistol = 'PISTOL',
    Force = 'FORCE',
    Buyround = 'BUYROUND'
}



