/* tslint:disable */
/* eslint-disable */
/**
 * csgo-stratbook api
 * Stratbook REST API
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { GetTeamResponse } from './get-team-response';

/**
 * 
 * @export
 * @interface GetUserResponse
 */
export interface GetUserResponse {
    /**
     * 
     * @type {string}
     * @memberof GetUserResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof GetUserResponse
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof GetUserResponse
     */
    avatar: string;
    /**
     * 
     * @type {GetTeamResponse}
     * @memberof GetUserResponse
     */
    team: GetTeamResponse;
    /**
     * 
     * @type {boolean}
     * @memberof GetUserResponse
     */
    completedTutorial: boolean;
}


