/* tslint:disable */
/* eslint-disable */
/**
 * csgo-stratbook api
 * Stratbook REST API
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RegisterUserResponse
 */
export interface RegisterUserResponse {
    /**
     * 
     * @type {string}
     * @memberof RegisterUserResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterUserResponse
     */
    email: string;
    /**
     * Debug: Email confirmation token
     * @type {string}
     * @memberof RegisterUserResponse
     */
    emailToken?: string;
}


