name: Deploy to Heroku staging environment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Using node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing dependencies
        run: npm ci
        working-directory: client
      - name: Building application
        run: npm run build:staging --if-present
        working-directory: client
      - name: Add heroku remote origin
        run: git remote add heroku-staging https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/csstrats-app.git
      - run: git add -A && git commit -m "Updated code"
      - name: Deploy to Heroku staging
        run: git push heroku-staging `git subtree split --prefix server master`:master --force